In [1]:
import numpy as np
from sklearn import preprocessing

data = np.array([[3, -1.5,  2, -5.4], [0,  4,  -0.3, 2.1], [1,  3.3, -1.9, -4.3]])

print(data)

[[ 3.  -1.5  2.  -5.4]
 [ 0.   4.  -0.3  2.1]
 [ 1.   3.3 -1.9 -4.3]]


In [2]:
#Scaling
data_scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled = data_scaler.fit_transform(data)

print("Min: ",data.min(axis=0))
print("Max: ",data.max(axis=0))

print("Min: ",data_scaled.min(axis=0))
print("Max: ",data_scaled.max(axis=0))

print(data_scaled)

Min:  [ 0.  -1.5 -1.9 -5.4]
Max:  [3.  4.  2.  2.1]
Min:  [0. 0. 0. 0.]
Max:  [1. 1. 1. 1.]
[[1.         0.         1.         0.        ]
 [0.         1.         0.41025641 1.        ]
 [0.33333333 0.87272727 0.         0.14666667]]
