In [2]:
import numpy as np
from sklearn.preprocessing import Imputer
import pandas as pd


data = np.array([[1,4,np.nan],[4,6,np.nan],[-3,5,2]])

print(data,"\n")

# Imputing with mean-strategy
imp = Imputer(strategy='mean')
print(imp.fit_transform(data),'\n')

# Imputing with most-frequent-strategy
imp = Imputer(strategy='most_frequent')
print(imp.fit_transform(data))

[[ 1.  4. nan]
 [ 4.  6. nan]
 [-3.  5.  2.]] 

[[ 1.  4.  2.]
 [ 4.  6.  2.]
 [-3.  5.  2.]] 

[[ 1.  4.  2.]
 [ 4.  6.  2.]
 [-3.  5.  2.]]


c:\users\insakum46\appdata\local\programs\python\python36\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
c:\users\insakum46\appdata\local\programs\python\python36\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
